"""empty message

Revision ID: 83b6b7cc1ad4
Revises: 587aa6a4d462
Create Date: 2024-12-12 19:46:21.702815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b6b7cc1ad4'
down_revision = '587aa6a4d462'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        batch_op.drop_column('discount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.FLOAT(), nullable=True))
        batch_op.drop_column('discount_percentage')

    # ### end Alembic commands ###
